[2024-07-27 18:21:27 -0400] [17325] [INFO] Starting gunicorn 22.0.0
[2024-07-27 18:21:27 -0400] [17325] [INFO] Listening at: http://0.0.0.0:8080 (17325)
[2024-07-27 18:21:27 -0400] [17325] [INFO] Using worker: sync
[2024-07-27 18:21:27 -0400] [17352] [INFO] Booting worker with pid: 17352
[2024-07-27 18:21:27 -0400] [17352] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/Users/treneese/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2024-07-27 18:21:27 -0400] [17352] [INFO] Worker exiting (pid: 17352)
[2024-07-27 18:21:27 -0400] [17325] [ERROR] Worker (pid:17352) exited with code 3
[2024-07-27 18:21:27 -0400] [17325] [ERROR] Shutting down: Master
[2024-07-27 18:21:27 -0400] [17325] [ERROR] Reason: Worker failed to boot.
[2024-07-27 18:48:14 -0400] [20334] [INFO] Starting gunicorn 22.0.0
[2024-07-27 18:48:14 -0400] [20334] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2024-07-27 18:48:14 -0400] [20334] [ERROR] Retrying in 1 second.
[2024-07-27 18:48:15 -0400] [20334] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2024-07-27 18:48:15 -0400] [20334] [ERROR] Retrying in 1 second.
[2024-07-27 18:48:16 -0400] [20334] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2024-07-27 18:48:16 -0400] [20334] [ERROR] Retrying in 1 second.
[2024-07-27 18:48:17 -0400] [20334] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2024-07-27 18:48:17 -0400] [20334] [ERROR] Retrying in 1 second.
[2024-07-27 18:48:18 -0400] [20334] [ERROR] Connection in use: ('0.0.0.0', 8080)
[2024-07-27 18:48:18 -0400] [20334] [ERROR] Retrying in 1 second.
[2024-07-27 18:48:19 -0400] [20334] [ERROR] Can't connect to ('0.0.0.0', 8080)
